config/routes.rb
Rails.application.routes.draw do
    resources :stores
    resources :areas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    include ParseInfo
    self.abstract_class = true

end

app/models/area.rb
class Area < ApplicationRecord
    belongs_to :nation
    belongs_to :sido
    belongs_to :gugun
    belongs_to :local
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/gugun.rb
class Gugun < ApplicationRecord

end

app/models/local.rb
class Local < ApplicationRecord

end

app/models/nation.rb
class Nation < ApplicationRecord
    after_find :load_data
end

app/models/parse_info.rb
module ParseInfo
    # Only used at Nation, Gugun, Local model

    DIRECT_RETURN_CLASSES = [Integer, Float, TrueClass, FalseClass, NilClass, Array, Hash]
    def load_data
        data.each do |key, value|
            class_eval %Q(
                def #{key}
                    #{value} if #{value.class}.in? DIRECT_RETURN_CLASSES
                    '#{value}' if #{value.class} == String
                end
            )
        end
    end

    def data
        JSON.parse self.info
    end

    def labels
        json = JSON.parse self.info
        labels = json.keys
        labels.map{|s| s.to_sym}
    end
end

app/models/runtime.rb
class Runtime < ApplicationRecord
end

app/models/sido.rb
class Sido < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :grade
  belongs_to :runtime
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
    before_action :set_area, only: [:show, :edit, :update, :destroy]

    # GET /areas
    # GET /areas.json
    def index
        @areas = Area.all
    end

    # GET /areas/1
    # GET /areas/1.json
    def show
    end

    # GET /areas/new
    def new
        @area = Area.new
    end

    # GET /areas/1/edit
    def edit
    end

    # POST /areas
    # POST /areas.json
    def create
        @area = Area.new(area_params)

        respond_to do |format|
            if @area.save
                format.html { redirect_to @area, notice: 'Area was successfully created.' }
                format.json { render :show, status: :created, location: @area }
            else
                format.html { render :new }
                format.json { render json: @area.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /areas/1
    # PATCH/PUT /areas/1.json
    def update
        respond_to do |format|
            if @area.update(area_params)
                format.html { redirect_to @area, notice: 'Area was successfully updated.' }
                format.json { render :show, status: :ok, location: @area }
            else
                format.html { render :edit }
                format.json { render json: @area.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /areas/1
    # DELETE /areas/1.json
    def destroy
        @area.destroy
        respond_to do |format|
            format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
        @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
        params.require(:area).permit(:nation_id, :sido_id, :gugun_id, :local_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :grade_id, :runtime_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nation_id %>
    <%= form.text_field :nation_id, id: :area_nation_id %>
  </div>

  <div class="field">
    <%= form.label :sido_id %>
    <%= form.text_field :sido_id, id: :area_sido_id %>
  </div>

  <div class="field">
    <%= form.label :gugun_id %>
    <%= form.text_field :gugun_id, id: :area_gugun_id %>
  </div>

  <div class="field">
    <%= form.label :local_id %>
    <%= form.text_field :local_id, id: :area_local_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Nation</th>
      <th>Sido</th>
      <th>Gugun</th>
      <th>Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.nation %></td>
        <td><%= area.sido %></td>
        <td><%= area.gugun %></td>
        <td><%= area.local %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nation:</strong>
  <%= @area.nation %>
</p>

<p>
  <strong>Sido:</strong>
  <%= @area.sido %>
</p>

<p>
  <strong>Gugun:</strong>
  <%= @area.gugun %>
</p>

<p>
  <strong>Local:</strong>
  <%= @area.local %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>WecheckApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :store_name %>
  </div>

  <div class="field">
    <%= form.label :grade_id %>
    <%= form.text_field :grade_id, id: :store_grade_id %>
  </div>

  <div class="field">
    <%= form.label :runtime_id %>
    <%= form.text_field :runtime_id, id: :store_runtime_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Grade</th>
      <th>Runtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.grade %></td>
        <td><%= store.runtime %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @store.grade %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @store.runtime %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>